// Icon Configuration for Space4U
// Unified icon system using multiple libraries for better visual variety

// Lucide React - Primary icon library (clean, modern)
export {
  Home,
  Users,
  Brain,
  User,
  Activity,
  Heart,
  Sparkles,
  Building2,
  LogOut,
  LogIn,
  Settings,
  Bell,
  Check,
  CheckCheck,
  Trash2,
  X,
  Search,
  Plus,
  Minus,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowLeft,
  Calendar,
  Clock,
  Star,
  MessageCircle,
  Phone,
  Mail,
  MapPin,
  Camera,
  Edit,
  Save,
  Share,
  Download,
  Upload,
  Filter,
  Menu,
  MoreVertical,
  MoreHorizontal,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Shield,
  AlertTriangle,
  AlertCircle,
  Info,
  CheckCircle,
  XCircle,
  Loader2,
  RefreshCw,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Video,
  VideoOff,
  PhoneCall,
  PhoneOff,
  Battery,
  Wifi,
  Bluetooth,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Zap,
  Target,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  LineChart,
  Award,
  Trophy,
  Medal,
  Gift,
  BookOpen,
  FileText,
  Image,
  Music,
  Film,
  Gamepad2,
  Coffee,
  Leaf,
  Flower,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  StarHalf,
  Sunrise,
  Sunset,
  Compass,
  Map,
  Navigation,
  Locate,
  Reply,
  ReplyAll,
  Forward,
  RotateCw,
  Shuffle,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Volume,
  Volume1,
  Headphones,
  Radio,
  Disc,
  Speaker,
  Mic2,
  Ear,
  EarOff,
  Tv,
  MonitorSpeaker,
  Airplay,
  Cast,
  HardDrive,
  Server,
  Database,
  UploadCloud,
  DownloadCloud,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudDrizzle,
  Umbrella,
  Thermometer,
  Wind,
  Snowflake,
  Waves,
  Droplets,
  Gauge,
  Flame,
  Fuel,
  Fan,
  Lightbulb,
  LightbulbOff,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  WifiOff,
  BluetoothConnected,
  BluetoothSearching,
  Usb,
  HdmiPort,
  Keyboard,
  Mouse,
  Watch,
  Router,
  Settings2,
  Wrench,
  Hammer,
  Shovel,
  Axe,
  Paintbrush,
  Palette,
  Scissors,
  Brush,
  Eraser,
  Pipette,
  Move,
  FlipHorizontal,
  FlipVertical,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  Crop,
  Diamond,
  Club,
  Spade,
  Package,
  Truck,
  Plane,
  Train,
  Bus,
  Car,
  Ship,
  Bike,
  Navigation2,
  Crosshair,
  Radar,
  Microscope,
  Glasses,
  Cpu,
  MemoryStick,
  Moon,
  Sun,
  MoonStar,
  Globe,
  Send,
} from 'lucide-react'

// Heroicons React - Secondary icon library (solid and outline styles)
export {
  HomeIcon as HeroHome,
  UserIcon as HeroUser,
  Cog6ToothIcon as HeroCog,
  BellIcon as HeroBell,
  HeartIcon as HeroHeart,
  StarIcon as HeroStar,
  CheckIcon as HeroCheck,
  XMarkIcon as HeroXMark,
  ChevronDownIcon as HeroChevronDown,
  ChevronUpIcon as HeroChevronUp,
  ChevronLeftIcon as HeroChevronLeft,
  ChevronRightIcon as HeroChevronRight,
  ArrowRightIcon as HeroArrowRight,
  ArrowLeftIcon as HeroArrowLeft,
  CalendarIcon as HeroCalendar,
  ClockIcon as HeroClock,
  EyeIcon as HeroEye,
  EyeSlashIcon as HeroEyeSlash,
  LockClosedIcon as HeroLock,
  LockOpenIcon as HeroUnlock,
  ShieldCheckIcon as HeroShield,
  ExclamationTriangleIcon as HeroAlert,
  InformationCircleIcon as HeroInfo,
  CheckCircleIcon as HeroCheckCircle,
  XCircleIcon as HeroXCircle,
  PhotoIcon as HeroImage,
  CameraIcon as HeroCamera,
  MicrophoneIcon as HeroMic,
  SpeakerWaveIcon as HeroSpeaker,
  PlayIcon as HeroPlay,
  PauseIcon as HeroPause,
  MagnifyingGlassIcon as HeroSearch,
  Bars3Icon as HeroMenu,
  PlusIcon as HeroPlus,
  MinusIcon as HeroMinus,
  PencilIcon as HeroEdit,
  TrashIcon as HeroTrash,
  DocumentIcon as HeroFile,
  FolderIcon as HeroFolder,
  ChatBubbleLeftIcon as HeroMessage,
  PhoneIcon as HeroPhone,
  VideoCameraIcon as HeroVideo,
  MapPinIcon as HeroMapPin,
  GlobeAltIcon as HeroGlobe,
  LinkIcon as HeroLink,
  ArrowUpTrayIcon as HeroShare,
  ArrowDownTrayIcon as HeroDownload,
  CloudIcon as HeroCloud,
  MoonIcon as HeroMoon,
  SunIcon as HeroSun,
  ComputerDesktopIcon as HeroMonitor,
  DevicePhoneMobileIcon as HeroSmartphone,
  DeviceTabletIcon as HeroTablet,
  ComputerDesktopIcon as HeroLaptop,
  BoltIcon as HeroZap,
  CursorArrowRaysIcon as HeroTarget,
  ArrowTrendingUpIcon as HeroTrendingUp,
  ArrowTrendingDownIcon as HeroTrendingDown,
  ChartBarIcon as HeroBarChart,
  ChartPieIcon as HeroPieChart,
  ChartBarSquareIcon as HeroLineChart,
  TrophyIcon as HeroAward,
  GiftIcon as HeroGift,
  BookOpenIcon as HeroBookOpen,
  DocumentTextIcon as HeroFileText,
  MusicalNoteIcon as HeroMusic,
  FilmIcon as HeroFilm,
  PuzzlePieceIcon as HeroGamepad,
  SparklesIcon as HeroSparkles,
  ViewfinderCircleIcon as HeroViewfinderCircle,
  WalletIcon as HeroWallet,
  WrenchScrewdriverIcon as HeroWrenchScrewdriver,
  TrophyIcon as HeroCrown,
} from '@heroicons/react/24/outline'

// React Icons - Third icon library (comprehensive collection)
export {
  FaHome as FaHome,
  FaUser as FaUser,
  FaCog as FaCog,
  FaBell as FaBell,
  FaHeart as FaHeart,
  FaStar as FaStar,
  FaCheck as FaCheck,
  FaTimes as FaX,
  FaChevronDown as FaChevronDown,
  FaChevronUp as FaChevronUp,
  FaChevronLeft as FaChevronLeft,
  FaChevronRight as FaChevronRight,
  FaArrowRight as FaArrowRight,
  FaArrowLeft as FaArrowLeft,
  FaCalendar as FaCalendar,
  FaClock as FaClock,
  FaEye as FaEye,
  FaEyeSlash as FaEyeSlash,
  FaLock as FaLock,
  FaUnlock as FaUnlock,
  FaExclamationTriangle as FaAlert,
  FaInfoCircle as FaInfo,
  FaCheckCircle as FaCheckCircle,
  FaTimesCircle as FaXCircle,
  FaImage as FaImage,
  FaCamera as FaCamera,
  FaMicrophone as FaMic,
  FaVolumeUp as FaSpeaker,
  FaPlay as FaPlay,
  FaPause as FaPause,
  FaSearch as FaSearch,
  FaBars as FaMenu,
  FaPlus as FaPlus,
  FaMinus as FaMinus,
  FaEdit as FaEdit,
  FaTrash as FaTrash,
  FaFile as FaFile,
  FaFolder as FaFolder,
  FaComment as FaMessage,
  FaPhone as FaPhone,
  FaVideo as FaVideo,
  FaMapMarker as FaMapPin,
  FaGlobe as FaGlobe,
  FaLink as FaLink,
  FaShare as FaShare,
  FaDownload as FaDownload,
  FaCloud as FaCloud,
  FaMoon as FaMoon,
  FaSun as FaSun,
  FaDesktop as FaMonitor,
  FaMobile as FaSmartphone,
  FaTablet as FaTablet,
  FaLaptop as FaLaptop,
  FaBolt as FaZap,
  FaBullseye as FaTarget,
  FaTrophy as FaAward,
  FaGift as FaGift,
  FaBook as FaBookOpen,
  FaMusic as FaMusic,
  FaFilm as FaFilm,
  FaGamepad as FaGamepad,
  FaCoffee as FaCoffee,
  FaLeaf as FaLeaf,
  FaMagic as FaSparkles,
} from 'react-icons/fa'